---
title: "Highlights"

---
# 2022 Literature Highlights 
Brown-Peterson NJ, Millender AK. 2022. The Reproductive Biology of Red Snapper in Mississippi Waters. SEDAR74-DW-9 SEDAR, North Charleston, SC 34 p. https://sedarweb.org/documents/sedar-74-dw-09-the-reproductive-biology-of-red-snapper-in-mississippi-waters/        

Brown-Peterson NJ, Wu W, Slife C, Dillon KS, Leontiou AJ. 2022. Variations in Red Snapper oocyte development and spawning in relation to environmental and habitat parameters. Environmental Biology of Fishes 105(7):797-819. https://doi.org/10.1007/s10641-022-01287-9        

Domínguez-Petit R, García-Fernández C, Leonarduzzi E, Rodrigues K, Macchi GJ. 2022. Parental Effects and Reproductive Potential of Fish and Marine Invertebrates: Cross-Generational Impact of Environmental Experiences. Fishes 7(4):188. https://www.mdpi.com/2410-3888/7/4/188        

Fish T, Wolf N, Smeltz TS, Harris BP, Planas JV. 2022. Reproductive biology of female Pacific halibut (Hippoglossus stenolepis) in the Gulf of Alaska. Frontiers in Marine Science 9:801759. https://doi.org/10.3389/fmars.2022.801759       

Galbraith JK, Katherine E. Bemis, William E. Bemis, Heath S. Cook, Wuenschel MJ. 2022. Identifications, distributions, and life history of four species of Seriola (Carangiformes: Carangidae) in the western North Atlantic based on contemporary and historical data. NOAA Professional Paper NMFS 22:1-42. https://doi.org/10.7755/PP.22       

Heins DC, Brown-Peterson NJ. 2022. The reproductive biology of small fishes and the clutch concept: Combining macroscopic and histological approaches. Aquaculture, Fish and Fisheries 2(4):253-264.    https://onlinelibrary.wiley.com/doi/abs/10.1002/aff2.49       

Jasonowicz AJ, Simeon A, Zahm M, Cabau C, Klopp C, Roques C, Iampietro C, Lluch J, Donnadieu C, Parrinello H, Drinan DP, Hauser L, Guiguen Y, Planas JV. 2022. Generation of a chromosome-level genome assembly for Pacific halibut (Hippoglossus stenolepis) and characterization of its sex-determining genomic region. Molecular Ecology Resources 22(7):2685-2700. https://doi.org/10.1111/1755-0998.13641       

Kashef NS, Stafford DM, Sogard SM, Garza JC, Field JC, Gilbert-Horvath EA. 2023. Multiple-brooding rockfishes (Sebastes spp.) can utilize stored sperm from individual sires to fertilize consecutive broods. Journal of Fish Biology n/a(n/a). https://doi.org/10.1111/jfb.15341       

Loher T, McCarthy O, Sadorus LL, Erikson LM, Simeon A, Drinan DP, Hauser L, Planas JV, Stewart IJ. 2022. A Test of Deriving Sex-Composition Data for the Directed Pacific Halibut Fishery via At-Sea Marking. Marine and Coastal Fisheries 14(4):e10218. https://doi.org/10.1002/mcf2.10218        

Lowerre-Barbieri, S. CF, Brown-Peterson N, Moncrief-Cox H, Barnett B. 2022. Best practices for standardized reproductive data and methodology to estimate reproductive parameters for Red Snapper in the Gulf of Mexico. SEDAR74-DW-43 SEDAR, North Charleston, SC 43 p. http://sedarweb.org/docs/wpapers/S74_DW_36_Repro_best%20practices%20report%20final_30_June_2022.v2.pdf        

McBride RS, Fairchild EA, Press YK, Elzey SP, Adams CF, Bentzen P. 2022. A Life History Study of Atlantic Wolffish Resolves Bias and Imprecision in Length- and Age-at-Maturity Schedules by Recognizing Abortive Maturation. Marine and Coastal Fisheries 14(5):e10222. https://doi.org/10.1002/mcf2.10222       

McBride RS, Maynard GA, Elzey SP, Hennen DR, Tholke EK, Runnebaum JM, McGuire CH. 2022. Evaluating growth dimorphism, maturation, and skip spawning of Atlantic halibut in the Gulf of Maine using a collaborative research approach. Journal of Northwest Atlantic Fishery Science 53:57-77. https://doi.org/10.2960/J.v53.m736        

McBride RS, Zemeckis DR, DeCelles GR, Ames T, Andrushchenko I, Kerr L, Miller AS, Cadrin SX. Life history (Chapter 5). In: McBride RS, Smedbol RK, editors. An Interdisciplinary Review of Atlantic Cod (Gadus morhua) Stock Structure in the Western North Atlantic Ocean. NOAA Technical Memorandum NMFS-NE-273. Woods Hole, Massachusetts: US Department of Commerce, National Oceanic and Atmospheric Administration, National Marine Fisheries Service, Northeast Fisheries Science Center; 2022. p. 83-129.        

McElroy WD, Tholke EK, Wuenschel MJ, Robillard E. 2022. Life History Assessment of Cusk, a Data-Poor Species, in U.S. Waters. Marine and Coastal Fisheries 14(5):e10223. https://doi.org/10.1002/mcf2.10223        

Millender AK, Higgs JM, Brown-Peterson NJ, Andres MJ, Franks JS. 2022. Life History of Swordfish, Xiphias gladius, Caught in the Northern Gulf of Mexico. Gulf and Caribbean Research 33(1):GCFI24-GCFI37. https://doi.org/10.18785/gcr.3301.09        

Min MA, Head MA, Cope JM, Hastie JD, Flores SM. 2022. Limitations and applications of macroscopic maturity analyses: a comparison of histological and visual maturity for three west coast groundfish species. Environmental Biology of Fishes 105:193-211. https://doi.org/10.1007/s10641-021-01208-2       

Pacicco AE, Brown-Peterson NJ, Murie DJ, Allman RJ, Snodgrass D, Franks JS. 2023. Reproductive biology of yellowfin tuna (Thunnus albacares) in the northcentral U.S. Gulf of Mexico. Fisheries Research 261:106620. https://www.sciencedirect.com/science/article/pii/S0165783623000139       

Pardee C, Wiley J, Schemmel E, Fendrick T, Giglio J. 2022. Comparative demography of four large-bodied surgeonfish. Environmental Biology of Fishes 105(2):231-245. https://doi.org/10.1007/s10641-022-01216-w        

Reed EM, Brown-Peterson NJ, DeMartini EE, Andrews AH. 2023. Effects of data sources and biological criteria on length-at-maturity estimates and spawning periodicity of the commercially important Hawaiian snapper, Etelis coruscans. Frontiers in Marine Science 10. https://www.frontiersin.org/articles/10.3389/fmars.2023.1102388       

Slesinger E, Bates K, Wuenschel M, Saba GK. 2022. Regional differences in energy allocation of black sea bass (Centropristis striata) along the US Northeast Shelf (36°N - 42°N) and throughout the spawning season. Journal of Fish Biology n/a(n/a). https://doi.org/10.1111/jfb.15023        

TenBrink T, Neidetcher S, Arrington M, Benson I, Conrath C, Helser T. 2022. Fourier transform near infrared spectroscopy as a tool to predict spawning status in Alaskan fishes with variable reproductive strategies. Journal of Near Infrared Spectroscopy 30(4):179-188.  https://journals.sagepub.com/doi/abs/10.1177/09670335221097005        

TenBrink TT. 2022. Delineating yellowfin sole (Limanda aspera) reproduction in the northern Bering Sea provides information across the eastern Bering Sea continental shelf. Fisheries Research 252:106335. https://www.sciencedirect.com/science/article/pii/S0165783622001126       

Zokan MA, David M. Wyanski, D. Byron White, Sedberry GR. 2022. Life history of the spotted moray (Gymnothorax moringa) off the Atlantic coast of the southeastern United States: age, growth, and reproduction. Fishery Bulletin 120(3-4):195-204. https://doi.org/10.7755/FB.120.3-4.1        


# 2021 Literature Highlights 
Fish, T., Wolf, N., Harris, B.P. and Planas, J.V., 2020. A comprehensive description of oocyte developmental stages in Pacific halibut, Hippoglossus stenolepis. Journal of Fish Biology, 97(6), pp.1880-1885.https://doi.org/10.3389/fmars.2022.

Jasonowicz, A.J., Simeon, A., Zahm, M., Cabau, C., Klopp, C., Roques, C., Iampietro, C., Lluch, J., Donnadieu, C., Parrinello, H. and Drinan, D.P., 2022. Generation of a chromosome‐level genome assembly for Pacific halibut (Hippoglossus stenolepis) and characterization of its sex‐determining genomic region. Molecular Ecology Resources. https://doi.org/10.1111/1755-0998.13641.

McBride, R.S., Fairchild, E.A., Press, Y.K., Elzey, S.P., Adams, C.F. and Bentzen, P., 2022. A Life History Study of Atlantic Wolffish Resolves Bias and Imprecision in Length‐and Age‐at‐Maturity Schedules by Recognizing Abortive Maturation. Marine and Coastal Fisheries, 14(5), p.e10222. https://doi.org/10.1002/mcf2.10222 

McBride, R.S., Maynard, G.A., Elzey, S.P., Hennen, D.R., Tholke, E.K., Runnebaum, J.M. and McGuire, C.H., 2022. Evaluating growth dimorphism, maturation, and skip spawning of Atlantic halibut in the Gulf of Maine using a collaborative research approach. J. Northw. Atl. Fish. Sci, 53, pp.57-77. [available here](https://journal.nafo.int/dnn/Volumes/Articles/ID/676/Evaluating-growth-dimorphism-maturation-and-skip-spawning-of-Atlantic-halibut-in-the-Gulf-of-Maine-using-a-collaborative-research-approach)

# 2021 Literature Highlights
[endnote library](https://drive.google.com/drive/folders/12jP4FuEKeZcY1bcH6h7AC8mbl9HezUnO?usp=sharing)

Beyer S., Alonzo S. H., Sogard S. M. 2021. Zero, one or more broods: reproductive plasticity in response to temperature, food, and body size in the live-bearing rosy rockfish Sebastes rosaceus. Marine Ecology Progress Series, 669. https://doi.org/10.3354/meps13718

Biggs C., Erisman B. 2021. Transmission loss of Fish Spawning Vocalizations and the Detection Range of Passive Acoustic Sampling in Very Shallow Estuarine Environments. Estuaries and Coasts, 44: 2026–2038. https://doi.org/10.1007/s12237-021-00914-5.

Biggs C., Heyman W., Farmer N., Kobara S. i., Bolser D., Robinson J., Lowerre-Barbieri S., Erisman B. 2021. The importance of spawning behavior in understanding the vulnerability of exploited marine fishes in the U.S. Gulf of Mexico. Peerj, 9: e11814.

Binder B. M., Taylor J. C., Gregg K., Boswell K. M. 2021. Fish Spawning Aggregations in the Southeast Florida Coral Reef Ecosystem Conservation Area: A Case Study Synthesis of User Reports, Literature, and Field Validation Efforts. Frontiers in Marine Science, 8. https://www.frontiersin.org/article/10.3389/fmars.2021.671477.
Brown-Peterson, N.J., R.T. Leaf and A.J. Leontiou.  2021.  Importance of depth and artificial structure as predictors of female Red Snapper reproductive parameters. Transactions of the American Fisheries Society. 150(1):115-129. https://doi.org/10.1002/tafs.10277.

Caiger P. E., Lefebve L. S., Llopiz J. K. 2021. Growth and reproduction in mesopelagic fishes: a literature synthesis. ICES Journal of Marine Science. https://doi.org/10.1093/icesjms/fsaa247.

Carpi P., Loher T., Sadorus L., Forsberg J., Webster R., Planas J., Jasonowicz A., Stewart I., Hicks A. 2021. Ontogenetic and spawning migration of Pacific halibut: a review. Reviews in Fish Biology and Fisheries, 31: 879–908. https://doi.org/10.1007/s11160-021-09672-w.

Chenet T., Mancia A., Bono G., Falsone F., Scannella D., Vaccaro C., Baldi A., Catani M., Cavazzini A., Pasti L. 2021. Plastic ingestion by Atlantic horse mackerel (Trachurus trachurus) from central Mediterranean Sea: A potential cause for endocrine disruption. Environmental Pollution: 117449. https://www.sciencedirect.com/science/article/pii/S0269749121010319.

Claireaux M., dos Santos Schmidt T. C., Olsen E. M., Slotte A., Varpe Ø., Heino M., Enberg K. 2021. Eight decades of adaptive changes in herring reproductive investment: the joint effect of environment and exploitation. ICES Journal of Marine Science, 78: 631–639. https://doi.org/10.1093/icesjms/fsaa123.

Concannon C. A., Cross E. L., Jones L. F., Murray C. S., Matassa C. M., McBride R. S., Baumann H. 2021. Temperature-dependent effects on fecundity in a serial broadcast spawning fish after whole-life high CO2 exposure. ICES Journal of Marine Science. https://doi.org/10.1093/icesjms/fsab217.

Conrath C., Hulson P.-J. 2021. Temporal variability in the reproductive parameters of deepwater rockfishes in the Gulf of Alaska. Fisheries Research, 237: 105876.

Denechaud C., Geffen A. J., Smoliński S., Godiksen J. A. 2021. Otolith “spawning zones” across multiple Atlantic cod populations: Do they accurately record maturity and spawning? Plos One, 16: e0257218. https://doi.org/10.1371/journal.pone.0257218.

dos Santos Schmidt T. C., Hay D., Sundby S., Devine J., Óskarsson G., Slotte A., Wuenschel M., Lajus D., Johannessen A., van Damme C., Bucholtz R., Kjesbu O. 2021. Adult body growth and reproductive investment vary markedly within and across Atlantic and Pacific herring: a meta-analysis and review of 26 stocks. Reviews in Fish Biology and Fisheries, 31.

dos Santos Schmidt T. C., Thorsen A., Slotte A., Nøttestad L., Kjesbu O. 2021. First thorough assessment of de novo oocyte recruitment in a teleost serial spawner, the Northeast Atlantic mackerel (Scomber scombrus) case. Scientific Reports, 11.

Ferreri R., Genovese, S., Barra, M., Biagiotti, I., Bourdeix, J., De Felice, A., Gašparević, D., Hattab, T., Iglesias, M., Juretić, T., Leonori, I., Malavolti, S., Raykov, V., Saraux, C., Tičina, V., Ventero, A., Basilone, G. 2021. Variability in size at maturity of the European anchovy (Engraulis encrasicolus) in the Mediterranean Sea. Mediterranean Marine Science, 22: 858-870. https://archimer.ifremer.fr/doc/00745/85660/90788.pdf.

Ferreri R., Barra M., Gargano A., Aronica S., Bonanno A., Genovese S., Rumolo P., Basilone G. 2021. New Evaluation of Postovulatory Follicle Degeneration at High-Temperature Regimes Refines Criteria for the Identification of Spawning Cohorts in the European Anchovy (Engraulis encrasicolus). Animals, 11: 529. https://doi.org/10.3390/ani11020529.

Hôrková-Žitňanová K., Švolíková K., Haruštiaková D., Kováč V. 2021. A New Approach to Evaluate Reproductive Traits in Batch-Spawning Fishes of Indeterminate Fecundity and Asynchronous Oocyte Maturation. Reviews in Fisheries Science & Aquaculture: 1-35. https://doi.org/10.1080/23308249.2020.1863331.

Iqbal M. F., Liew H. J., Rahmah S. 2021. Dietary Protein Level Influenced Reproductive Development of Hoven’s carp Leptobarbus hoevenii Female Broodstock. Animal Feed Science and Technology: 115112. https://www.sciencedirect.com/science/article/pii/S0377840121002984.

Jansen T., Slotte A., Christina dos Santos Schmidt T., Reedtz Sparrevohn C., Arge Jacobsen J., Sigurd Kjesbu O. 2021. Bioenergetics of egg production in Northeast Atlantic mackerel reveal misconcepted perception of fecundity type and annual trends in spawning stock biomass. Progress in Oceanography: 102658. https://www.sciencedirect.com/science/article/pii/S0079661121001439.

K Forsgren, RS McBride, T Nakatsubo, TM Thys, CD Carson, E Tholke, L Kubicek, Potter I. 2021. Reproductive biology of the ocean sunfishes. In  The Ocean Sunfishes: Evolution, Biology and Conservation Ed. by  Thys T, Hays G, Houghton J. Boca Raton, FL, USA: CRC Press. pp:  87-104, https://doi.org/110.1201/9780429343360.

Lam L. S., Basnett B. L., Haltuch M. A., Cope J., Andrews K., Nichols K. M., Longo G. C., Samhouri J. F., Hamilton S. L. 2021. Geographic variability in lingcod Ophiodon elongatus life history and demography along the US West Coast: oceanographic drivers and management implications. Marine Ecology Progress Series, 670: 203-222. https://doi.org/10.3354/meps13750.

Leontiou A., Wu W., Brown-Peterson N. 2021. Immature and mature female Red Snapper habitat use in the north-central Gulf of Mexico. Regional Studies in Marine Science, 44: 101715. https://doi.org/10.1016/j.rsma.2021.101715.

Leontiou A., Wu W., Brown-Peterson N. 2021. The Role of Maturity in Artificial Habitat Selection by Female Red Snapper. Marine and Coastal Fisheries, 13: 332-344. https://doi.org/10.1002/mcf2.10160.

Marshall D., Bode M., Mangel M., Arlinghaus R., Dick E. 2021. Reproductive hyperallometry and managing the world’s fisheries. Proceedings of the National Academy of Sciences, 118: e2100695118. https://doi.org/10.1073/pnas.2100695118.

Meyer K. A., Schill D. J. 2021. The Gill-Oxygen Limitation Theory and size at maturity/maximum size relationships for salmonid populations occupying flowing waters. Journal of Fish Biology, 98: 44-49. https://onlinelibrary.wiley.com/doi/abs/10.1111/jfb.14555.
Min, M.A., Head, M.A., Cope, J.M. et al. 2022. Limitations and applications of macroscopic maturity analyses: a comparison of histological and visual maturity for three west coast groundfish species. Environ Biol Fish. https://doi.org/10.1007/s10641-021-01208-2
Mouchlianitis F. A., Schultz E. T., dos Santos Schmidt T. C., Davis J. P., Ganias K. 2021. Ovarian dynamics and fecundity regulation in blueback herring, Alosa aestivalis, from the Connecticut River, US. Journal of Applied Ichthyology, 37: 64-72. https://onlinelibrary.wiley.com/doi/abs/10.1111/jai.14128.

Pensinger L., Brown-Peterson N., Green C., Midway S. 2021. Reproductive biology of hardhead catfish Ariopsis felis: Evidence for overwintering oocytes. Journal of Fish Biology, 99. https://doi.org/10.1111/jfb.14717.

Poulet C., Paumier A., Lassalle G., Pierre M., Lambert P. 2021. Simulating upstream migration and spawning timing effects to allis shad reproductive success. Environmental Biology of Fishes. https://doi.org/10.1007/s10641-021-01151-2.

Reed E., Brown-Peterson N., DeMartini E., Andrews A. 2021. Reproductive Characteristics of Longtailed Red Snapper (Onaga, Etelis coruscans) in the Main Hawaiian Islands.

Rørvik C., Bogstad B., Ottersen G., Kjesbu O. 2021. Long-term interplay between harvest regimes and biophysical conditions may lead to persistent changes in age-at-sexual maturity of Northeast Arctic cod (Gadus morhua). Canadian Journal of Fisheries and Aquatic Sciences. https://doi.org/10.1139/cjfas-2021-0068.

Schemmel E. 2021. Size at maturity for yellow tang (Zebrasoma flavescens) from the Oahu, HI, aquarium fishery. Environmental Biology of Fishes, 104: 1139-1147. https://doi.org/10.1007/s10641-021-01142-3.

Schemmel E., Nichols R., Cruz E., Boyer J., Camacho F. 2021. Growth, mortality, and reproduction of the oblique-banded snapper (Pristipomoides zonatus) in Guam. Marine and Freshwater Research. https://doi.org/10.1071/MF21094.

Shackell N. L., Fisher J. A. D., den Heyer C. E., Hennen D. R., Seitz A. C., Le Bris A., Robert D., Kersula M. E., Cadrin S. X., McBride R. S., McGuire C. H., Kess T., Ransier K. T., Liu C., Czich A., Frank K. T. 2021. Spatial ecology of Atlantic halibut across the northwest Atlantic: A recovering species in an era of climate change. Reviews in Fisheries Science & Aquaculture: 1–25. https://doi.org/10.1080/23308249.2021.1948502.

TenBrink TT, TE Helser. 2021. Reproductive biology, size and age structure of Harlequin Rockfish: spatial analysis of life history traits. Marine and Coastal Fisheries 13: 463-477. DOI: 10.1002/mcf2.10172
