---
title: "Histology"
description: |
  Links to MARVLS histology workshops and trainings.
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---

## Atresia
Discussed at the Winter 2022 MARVLS Seminar. [Presentation in MARVLS shared drive](https://drive.google.com/file/d/1lfirHXjp-IO8wSaerQ9RbnxS6aG45Yev/view?usp=share_link) and [species examples](https://drive.google.com/drive/folders/10YSGg1fa-phidYaokwp58HohIO8Sl2lc?usp=share_link).


### Atresia Literature

Agius, C., & Roberts, R. J. 2003. Melano‐macrophage centres and their role in fish pathology. Journal of fish diseases, 26(9), 499-509

Besseau, L. and E. Faliex. 1994. Resorption of unemitted gametes in Lithognathus mormyrus (Sparidae, Teleostei): a possible synergic action of somatic and immune cells.  Cell and Tissue Research 276:123-132

Blazer, V. S. 2002. Histopathological assessment of gonadal tissue in wild fishes. Fish Physiology and Biochemistry, 26(1), 85-101.

Cek-Yalnız, S., Yilmaz, E. (2019). Atresia and apoptosis in pre- and postovulatory follicles of sharptooth catfish (clarias gariepinus, Burchell, 1822). Pakistan Journal of Zoology 51(1), 85-95. doi: 10.17582/journal.pjz/2019.51.1.85.95

Dominguez-Petit, R. A. Alonso-Fernandez, and F. Saborido-Rey. 2011. Incidence and significance of cystic structures in the ovaries of gadoid fish. Scientia Marina 75: 359-368.

Dominguez-Castanedo, O., M.C. Uribe, and T.M. Munoz-Campos. 2019. Morphological patterns of cell death in ovarian follicles of primary and secondary growth and postovulatory follicle complex of the annual killifish Millerichthys robustus (Cyprinodontiformes: Cynolebiidae). Journal of Morphology 2019: 1-14

Haslob, H., Kraus, G., Saborido-Rey, F., 2012. The dynamics of postovulatory follicle degeneration and oocyte growth in Baltic sprat. Journal of Sea Research 67 (1), 27-33.

Hsueh, A.J.W., H. Billig, and A. Tsafriri. 1994. Ovarian follicle atresia: A hormonally controlled apoptotic process. Endocrine Reviews 15: 707-724.

Hunter, J.R. and B.J. Macewicz. 1985. Measurement of spawning frequency in multiple spawning fishes. NOAA Technical Report NMFS (1985), pp. 79-94.

Kroemer, G., L. Galluzzi, P. Vandenabeele, J. Abrams, E.S. Alnemri, E.H. Baehrecke, M.V. Blagosklonny, W.S. El-Diery, P. Golstein, D.R. Green, M. Hengartner, R.A. Knight, S. Kumar, S.A. Lipton, W. Malorni, G. Nunez, M.E. Peter, J. Tschopp, J. Yuan, M. Piacentini, B. Zhivotovsky, and G. Melino. 2009. Classification of cell death: recommendations of the Nomenclature Committee on Cell Death 2009. Cell Death and Differentiation 16: 3-11. 

Kumar, R. and K.P. Joy. 2015. Melanins as biomarkers of ovarian follicular atresia in the catfish Heteropneustes fossilis: biochemical and histochemical characterization, seasonal variation, and hormone effects. Fish. Physiol. Biochem. 41: 761-722.

Miranda, A.C.L., N. Bazzoli, E. Rizzo, and Y. Sato. 1999. Ovarian follicular atresia in two teleost species: a histological and ultrastructural study. Tissue & Cell 31: 480-488. 

Santos, H.B., R.G. Thome, F.P. Arantes, Y. Sato, N. Bazzoli, and E. Rizzo. 2008. Ovarian follicular atresia is mediated by heterophagy, autophagy, and apoptosis in Prochilodus argenteus and Leporinus taeniatus (Teleostei: Characiformes). Theriogenology 2008: 1449-1460.

Ucuncu, S.I. and O. Cakici. 2009. Atresia and Apoptosis in Preovulatory Follicles in the Ovary of Danio rerio (Zebrafish). Turkish Journal of Fisheries and Aquatic Sciences 9: 215-221.

Witthames, P.R., A. Thorsen, and S. Kjesbu. 2010. The fate of vitellogenic follicles in experimentally monitored Atlantic cod, Gadus morhua (L.): Application to stock assessment. Fisheries Research 104: 27-37.

Wood, A.W., and G.J. Van Der Kraak. 2001. Apoptosis and ovarian function: Novel perspectives from the teleosts. Biology of Reproduction 64: 264-271.

Zhou, J., P. Xianwen, and M. Shuqi. 2019. Autophagy in ovarian follicular development and atresia.  International Journal of Biologica Sciences 15: 726-737.




        
## Parasites

Reviewed by Dr. Isaure de Buron at the Summer 2022 MARVLS Seminar. [Presentation in MARVLS shared drive](https://drive.google.com/file/d/1XBifNpSYsiBnBqWnj3LXlhIrHA8gqH7x/view?usp=sharing) and [references](https://drive.google.com/drive/folders/1K1esaJ8Mn90TAo6k0u0X3P12FJH5o7TF?usp=share_link).


## 2020 Virtual Histology Workshop

2020 Joint NSAW & MARVLS meeting: 4th National MARVLS Workshop rescheduled. In-person workshop canceled but a [virtual histology workshop was held](https://drive.google.com/drive/folders/1ppjix93fNMTv-5erjq1g_DGwFSxqWD_x?usp=sharing). [Results from virtual histology workshop](https://drive.google.com/file/d/1j2g_dVYebEBHjM1J1d2lgWCNZWcnH9KP/view?usp=sharing)